apiVersion: v1
kind: Service
metadata:
  name: mule-deployment
  labels:
    run: mule-deployment
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: jmx
    port: 1099
    targetPort: 1099
  - name: jolokia
    port: 8899
    targetPort: 8899
  selector:
    app: mule-deployment
  type: LoadBalancer
